root = "."

temp_dir = "tmp"

[build]

  cmd = "go build -o tmp/main.exe ./cmd"
  bin = "tmp/main.exe"
  delay = 1000
  exclude_dir = ["tmp", "vendor"]

[log]
  level = "debug"


[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"